### ISSUE TITLE
Documentación: diseño arquitectónico y procedimental

### ISSUE THREAD

**Issue by jasag** [jasag/Phytoliths-recognition-system#54]

**Comment by alvarag** [comment]
Comentarios sobre la documentación técnica actual.

[anexosC.pdf](https://github.com/jasag/Phytoliths-recognition-system/files/985887/anexosC.pdf)
[memoriaC.pdf](https://github.com/jasag/Phytoliths-recognition-system/files/985888/memoriaC.pdf)

**Comment by jasag** [comment]
Gracias por las correcciones.

**Comment by alvarag** [comment]
Acabo de caer en que en conceptos teóricos no aparece explicado lo que es un fitolito. Añade una pequeña sección con lo que es y algunas fotografías con los diversos tipos, las adjunto.
Además, pon alguna referencia de fitolitos como las que adjunto.

![image_280_](https://cloud.githubusercontent.com/assets/9881614/25940075/3681af58-3635-11e7-8d76-9d3d0806e426.jpg)
![image_496_](https://cloud.githubusercontent.com/assets/9881614/25940076/3682672c-3635-11e7-8243-6a01ec578bab.jpg)
![image_568_](https://cloud.githubusercontent.com/assets/9881614/25940074/368163fe-3635-11e7-9757-bb88955a6806.jpg)
![image_713_](https://cloud.githubusercontent.com/assets/9881614/25940072/36808434-3635-11e7-9f61-7ba27959aab1.jpg)
![image_790_](https://cloud.githubusercontent.com/assets/9881614/25940077/3683a38a-3635-11e7-9655-082e73a4d52f.jpg)
![image_854_](https://cloud.githubusercontent.com/assets/9881614/25940073/36807fca-3635-11e7-88f1-be40246f54f4.jpg)

[2005_International Code for Phytolith Nomenclature.pdf](https://github.com/jasag/Phytoliths-recognition-system/files/992343/2005_International.Code.for.Phytolith.Nomenclature.pdf)
