### ISSUE TITLE
Pérdida de calidad en guardado JPG

### ISSUE THREAD

**Issue by alvarag** [jasag/Phytoliths-recognition-system#55]
He estado etiquetando algunos fitolitos y veo que en la carpeta Default las imágenes se guardan con una calidad muy muy baja, ejemplos:

- De 2.6MB a 240KB
- De 2.9MB a 349KB

Revisa cómo está funcionando el código de guardado, tal vez puedas especificar la compresión del fichero JPG. Si es así elige la máxima calidad de scikit-image.

Es urgente puesto que espero que desde Barcelona puedan empezar mañana mismo a etiquetar fitolitos y sería aconsejable tener esto corregido para evitar problemas.

**Comment by jasag** [comment]
Estoy con ello ya. Trataré de dar con la solución lo antes posible.

**Comment by alvarag** [comment]
Perfecto, gracias

**Comment by jasag** [comment]
Bueno, he conseguido que se pueda guardar con la misma calidad la imagen. Excepto en los casos en los que la imagen original no se ha de formato JPG. En estos casos se puede observar una comprensión de unas 4 o 5 veces. Pero ahora mismo no sé cual podría ser la solución.

**Comment by alvarag** [comment]
Escribe aquí el código con el que estás guardando la imagen y lo echo un ojo.

**Comment by jasag** [comment]
Este sería la linea que guarda el código:

`io.imsave(image_path, image, quality=100)`

Donde _image_path_ es la ruta donde se guarda la imagen, ya con formato JPG, image es el array con los datos de la imagen y _quality_ es el parametro que indica que se guarde la imagen con el 100% de calidad.

Simplemente, lo que acabo de añadir es el parametro _quality_, que índica a la función de guardado que no reduzca la calidad. Así, funciona sin perdida de calidad cuando no se realiza conversión del formato de la imagen. Pero en las ocasiones que la imagen original es de otra extensión, por ejemplo TIF, se pierde calidad en la conversión al formato JPG.

**Comment by alvarag** [comment]
No me queda claro, ¿en JPG guarda bien y en TIF no?

**Comment by jasag** [comment]
El caso es que todas las imágenes se guardan en JPG. Por lo tanto, si cargas una imagen TIF, esta imagen se guardará con formato JPG. Lo que lleva un cambio de formato. Y también un cambio en el tamaño de la imagen a menos. Lo cual no sería una perdida de calidad.

**Comment by jasag** [comment]
Aunque el problema inicial que indicabas existía, porque _scikit_ hace una compresión al 75% del tamaño de la imagen, lo cual ya he solucionado con ese parametro. ¿No sé si me explico?

**Comment by alvarag** [comment]
Entonces ahora el guardado de JPG a JPG no pierde calidad, ¿cierto?

**Comment by jasag** [comment]
Con ese nuevo parámetro me consta que no. El tamaño de un ejemplo de foto original es de 2,55 MB, y de una nueva de 2,57 MB

**Comment by alvarag** [comment]
De acuerdo, damos por cerrada la issue.
