### ISSUE TITLE
Evaluar los resultados de YOLO con un primer dataset

### ISSUE THREAD

**Issue by jasag** [jasag/Phytoliths-recognition-system#61]

**Comment by alvarag** [comment]
En este sprint deberías entrenar YOLO con el dataset completo de Barcelona así como data-augmentation.

**Comment by jasag** [comment]
Visto que los resultados obtenidos con YOLO durante estas últimas semanas no han sido posibles de evaluar. Ya que no se ha sido capaz de obtener predicciones, porque el modelo no converge. Se dejará las conclusiones finales para la última semana.
