### ISSUE TITLE
Fitolitos etiquetados

### ISSUE THREAD

**Issue by alvarag** [jasag/Phytoliths-recognition-system#62]
Esta mañana he ayudado a Virginia a instalar el etiquetador y lo han estado utilizando. Débora ha trabajado en ello y, ahora mismo, se están subiendo la carpeta "rsc" al Dropbox.

Echa un ojo a ver si lo han hecho bien, sino les decimos mañana para que revisen alguna foto que hayan hecho incorrectamente.

**Comment by jasag** [comment]
Muy bien. He mirado algunas imágenes etiquetadas y parece que por ahora lo están utilizando correctamente. Muchas gracias.

**Comment by alvarag** [comment]
Revisa si la solución que te he dado para las coordenadas te cuadra y, si es así, cierra esta issue.
