### ISSUE TITLE
Entrenar el clasificador con los fitolitos reetiquetados

### ISSUE THREAD

**Issue by jasag** [jasag/Phytoliths-recognition-system#68]

**Comment by alvarag** [comment]
Ha estado todo el fin de semana entrenando, calculo unas 55 horas. Lo he parado ahora, dime qué archivos son los que necesitas para poder comprobar si ha convergido la red.

```
Finish 219 epoch(es)
step 658 - loss 1.20035982131958 - moving ave loss 1.2626463216835104
step 659 - loss 1.4644320011138916 - moving ave loss 1.2828248896265486
step 660 - loss 1.2036800384521484 - moving ave loss 1.2749104045091086
Finish 220 epoch(es)
step 661 - loss 1.1344131231307983 - moving ave loss 1.2608606763712775
step 662 - loss 1.3718047142028809 - moving ave loss 1.2719550801544377
```

**Comment by jasag** [comment]
No sé si habrá convergido ya. Puesto que el error puede que todavía no se haya estabilizado y continue bajando. Pero la progresión del error tiene bastante buena apariencia. Por otro lado, el último _checkpoint_, o estado de la red del que podemos partir, está 12 _epochs_ atrás: 

```
Finish 207 epoch(es)
step 622 - loss 1.8270580768585205 - moving ave loss 1.7482966814331986
step 623 - loss 2.1752519607543945 - moving ave loss 1.790992209365318
step 624 - loss 1.4568427801132202 - moving ave loss 1.7575772664401084
Finish 208 epoch(es)
step 625 - loss 1.6025184392929077 - moving ave loss 1.7420713837253883
Checkpoint at step 625
step 626 - loss 1.7589023113250732 - moving ave loss 1.743754476485357
step 627 - loss 1.3427557945251465 - moving ave loss 1.7036546082893358
Finish 209 epoch(es)
```

Aun así, la única manera de comprobar si ha convergido es tratando de predecir una imagen. Para ello, puedes abrir una sesión de Python y escribir:

```
from darkflow.net.build import TFNet
import cv2

options = {"model": "cfg/yolo-1c.cfg", "load": -1, "threshold": 0.0}

tfnet = TFNet(options)

imgcv = cv2.imread("./sample_img/dog.jpg") # Cambiar por ruta de la imagen
result = tfnet.return_predict(imgcv)
print(result)
```

**Comment by alvarag** [comment]
Puesto que en unas 12 horas sólo ha grabado un checkpoint, creo que igual deberíamos hacer copia cada menos tiempo, ¿cuál es la opción? Igual backup cada 1000 sería más aconsejable.

**Comment by jasag** [comment]
Si. O incluso cada menos. Es un poco en función de cuanto almacenamiento libre tengas en tu ordenador y cada cuanto se completa una _epoch_ en el entrenamiento, o al menos yo lo calculo en función de eso. 

Pongamos que quieres hacer una copia por hora y tu ordenador es capaz de completar 60 _epochs_ por hora. Como lo estamos entrenando con 55 imágenes, en cada epoch utilizas las 55 imágenes para el entrenamiento. Y en la opción __--save__ indicas cada cuantas imágenes procesadas realizas la copia. Por lo tanto, tendrías que indicar 60*55 = 3300.

**Comment by alvarag** [comment]
Luego lo lanzo de nuevo, ¿ha habido mejoría con lo entrenado durante esta noche?

**Comment by jasag** [comment]
Si. Estoy tratando de entrenar la versión _tiny_. Y en una sola noche ha llegado a un error entorno a 0.1. Pero todavía no es capaz de obtener etiquetas. Hay que tener en cuenta que he realizado sobre unas 700 _epochs_. Por lo que reentrenare dicho modelo durante estos días para tratar de bajar el error a un valor cercano a cero.

No me da mucha confianza la versión tiny, pero es la única manera a partir de la cual puedo llegar a un número más significativo de _epochs_.

**Comment by jasag** [comment]
Mañana trato de adjuntar, por aquí, parte de la salida del entrenamiento. Para hacerlo un poco más visible.

**Comment by alvarag** [comment]
He esperado hasta que ha completado el checkpoint:

```
Finish 49 epoch(es)
step 898 - loss 1.3402414321899414 - moving ave loss 0.9211810019262008
step 899 - loss 0.7466658353805542 - moving ave loss 0.9037294852716362
step 900 - loss 0.4975850284099579 - moving ave loss 0.8631150395854684
Finish 50 epoch(es)
step 901 - loss 0.7326613664627075 - moving ave loss 0.8500696722731924
step 902 - loss 1.0721814632415771 - moving ave loss 0.8722808513700309
step 903 - loss 0.7741212844848633 - moving ave loss 0.8624648946815141
Finish 51 epoch(es)
step 904 - loss 1.0873507261276245 - moving ave loss 0.8849534778261252
step 905 - loss 0.959801971912384 - moving ave loss 0.8924383272347511
Checkpoint at step 905
```

En el dropbox lo dejo.
