### ISSUE TITLE
Documentación: Complejidad de la tarea

### ISSUE THREAD

**Issue by alvarag** [jasag/Phytoliths-recognition-system#69]
En la memoria, puedes poner una sección donde pongas de relieve la dificultad de la tarea de reconocimiento. Ahí puedes hablar de que son en 3D, los hay de distintas formas (incluso en el mismo tipo), etc.
Además, puedes poner varios fitolitos, recortados como te los deja la aplicación, (del mismo tipo) todos en una figura (con \subfigure) y así se verá toda la variabilidad de formas que hay.

**Comment by alvarag** [comment]
@jasag sube una versión de la documentación con lo que tengas hasta ahora durante el día de hoy para que @joseFranciscoDiez  y yo podamos revisarla antes de la reunión.

Por cierto, el jueves a las 19:00 como el jueves pasado.

**Comment by jasag** [comment]
De acuerdo. ¿ Para que hora la necesitáis?

**Comment by alvarag** [comment]
Mañana a lo largo del día/tarde y así podemos comentarte cosas en la reunión del jueves por la tarde.

**Comment by jasag** [comment]
Bien. Lo suelo mantener bastante actualizado de todas formas.

**Comment by alvarag** [comment]
Adjunto los dos documentos con comentarios:

[anexosS.pdf](https://github.com/jasag/Phytoliths-recognition-system/files/1047337/anexosS.pdf)
[memoriaS.pdf](https://github.com/jasag/Phytoliths-recognition-system/files/1047338/memoriaS.pdf)

**Comment by jasag** [comment]
Muchas gracias. Me pongo con ello.
