### ISSUE TITLE
Redimensionar el conjunto de entrenamiento a 448x448px

### ISSUE THREAD

**Issue by alvarag** [jasag/Phytoliths-recognition-system#70]
Buenos días,

He estado leyendo en detalle el artículo del [YOLO](https://arxiv.org/abs/1612.08242) y creo que una de las claves de su éxito es cómo funciona internamente. Su proceso de detección viene determinado por las celdas que hace (cuadrícula/segmentación) para comprobar si pertenece o no a un objeto.

Por ello me gustaría hacer una última prueba de entrenamiento con las imágenes reducidas a 448x448 píxeles. Esto exige recortar la foto porque actualmente las tenemos en formato panorámico y deberían ser cuadradas como las de ImageNet. Y posteriormente reducirlas de tamaño a 448 de ancho

Ejemplo:
![2017_5_17_17_56image_7636](https://cloud.githubusercontent.com/assets/9881614/26622090/8916f570-45e9-11e7-81c2-29af453743b3.jpg)

El redimensionado exige modificar las coordenadas, ¿podrías tenerlo para esta tarde y así poder dejar lanzado este experimento y comprobar cómo funciona?

Saludos,

**Comment by alvarag** [comment]
Para acelerar el proceso, he procesado yo todas las imágenes y las he etiquetado. Pero parece haber un error con la nueva versión del etiquetador que hay en Git porque las coordenadas las has calculado mal y esto ha hecho que lo que he estado haciendo no valga para nada.

En el adjunto van las imágenes que he estado etiquetando y que ha calculado mal.

[img.zip](https://github.com/jasag/Phytoliths-recognition-system/files/1040981/img.zip)

**Comment by jasag** [comment]
Vale. Lo primero es que el código que se encuentra actualmente en Git es la primera versión de este. Trataré de subir en el día de hoy la nueva versión, pero quería pegarlo un repaso antes. Y, segundo,  ¿Que etiquetador estas utilizando: el que se encuentra en la _release_ o en el código, que no me queda claro? Es por acotar errores.

En cualquier caso, tanto en un sitio como en otro el etiquetador debería ser el mismo. Pero lo reviso de todas formas.

Por último, creo y espero que no es necesario reetiquetar manualmente las imágenes tras redimensionarlas. Ese proceso lo tengo automatizado en el notebook de _data_augmentation_ por lo que se puede reaprovechar. Trataré de adjuntarte, si estoy en lo cierto, las nueva imágenes con ese formato lo antes posible durante la tarde de hoy. 

Muchas gracias de todas formas por todos los detalles de los que te has cercionado.

**Comment by alvarag** [comment]
He cogido el etiquetador que está subido (el último disponible), no el de la release. Pensé que era el más actualizado y así podía probar que todo funcionase correctamente.

Yo también creo que no es necesario reetiquetar todas las imágenes, sólo sería hacer un crop (para hacerlas cuadradas) y luego redimensionar para dejar a 480x480. Si lo tienes antes de las 19:00 lo pongo a entrenar para ver qué sale tras esta noche.

**Comment by jasag** [comment]
Acabo de subirlo en un archivo comprimido en el dropbox, dentro de la carpeta rescaled: _picsCompressedRescaled.zip_

**Comment by alvarag** [comment]
Veo que los has reescalado directamente, así que has cambiado la razón de aspecto: ahora todos están más "achatados/estilizados" por así decirlo.

Tampoco creo que tenga mucha influencia porque los fitolitos no guardan dicha razón: los hay alargados, estrechos, gordos... y además dependen de cómo estaba la cámara. Pero si funcionase se podría hacer un "crop" primero y luego un reescalado, como te comentaba.

No obstante, lo voy a lanzar hoy a ver si se nota alguna mejoría.

Gracias.

**Comment by jasag** [comment]
No había leído ese apunte, perdona. Entonces, si no entiendo mal lo que quieres es recortar las imágenes a los primeros 480 x 480 píxeles. En lugar de reescalarlas, no?

**Comment by alvarag** [comment]
Mi idea era:

- Recortar todas a 1920x1920: cambiar formato a cuadrado.
- Reescalarlas a 480x480.

En el primer paso no hace falta modificar las coordenadas y en el segundo paso si.

No obstante los resultados de la red con esta nueva configuración tampoco me han parecido mucho mejores que la anterior.

**Comment by alvarag** [comment]
Creo que esta issue podría cerrarse puesto que no vamos a utilizar darkflow
