### ISSUE TITLE
Crear nueva release con el etiquetador actual

### ISSUE THREAD

**Issue by alvarag** [jasag/Phytoliths-recognition-system#75]
He estado probando el etiquetador en Linux y funciona correctamente (siempre y cuando utilices Chrome claro). Así que actualiza los requisitos del etiquetador para indicar que se puede utilizar tanto en Windows como en Linux.

También haz una nueva release con el código para que lo utilice el compañero de Débora, así solo se tiene que bajar la release en vez de todo el repositorio.

**Comment by jasag** [comment]
De acuerdo, la crearé antes de que finalice el fin de semana.

**Comment by jasag** [comment]
@alvarag realizada la nueva _release_. Trataré de actualizar los requisitos durante esta semana.

**Comment by alvarag** [comment]
Gracias, se puede cerrar esta issue.
