### ISSUE TITLE
Probar sliding window multiresolución y multiratio

### ISSUE THREAD

**Issue by joseFranciscoDiez** [jasag/Phytoliths-recognition-system#79]
[Sliding Window.ipynb.zip](https://github.com/jasag/Phytoliths-recognition-system/files/1099588/Sliding.Window.ipynb.zip)

**Comment by jasag** [comment]
Muchas gracias José Francisco.

**Comment by jasag** [comment]
Esta funcionalidad finalmente no sé ha implementado debido a que lleva consigo diversas problemáticas en la transformación de coordenadas.
