### ISSUE TITLE
Documentación: conclusiones y lineas futuras

### ISSUE THREAD

**Issue by jasag** [jasag/Phytoliths-recognition-system#81]

**Comment by alvarag** [comment]
Cuando tengas lista la versión "definitiva" de la memoria nos dices para revisarlo.

**Comment by jasag** [comment]
Estoy con ello. Os digo.

**Comment by jasag** [comment]
@alvarag @joseFranciscoDiez Trataré de tenerlo para mañana por la tarde.

**Comment by alvarag** [comment]
Quedamos a la espera

**Comment by alvarag** [comment]
Para imprimir la memoria mejor que las URLs no tengan colores.
\usepackage[colorlinks=false]{hyperref}

**Comment by jasag** [comment]
De acuerdo, gracias. Lo cambio ya.

**Comment by jasag** [comment]
Si cambio la línea que me indicas. Me queda así:
![captura](https://user-images.githubusercontent.com/15627268/27725760-1e5c2880-5d78-11e7-8ef1-7e6443f857f1.PNG)

¿Qué tal si pongo todos los colores iguales a negro?
`\usepackage[colorlinks]{hyperref}
\hypersetup{
	allcolors = {black}
}
`

**Comment by alvarag** [comment]
No me acordaba de eso, prueba con: \usepackage[hidelinks]{hyperref}

**Comment by jasag** [comment]
Parece que ahora sí.

![captura](https://user-images.githubusercontent.com/15627268/27726006-f7825486-5d78-11e7-816a-59e626ae03f0.PNG)
