### ISSUE TITLE
Correcciones menores sobre anexos

### ISSUE THREAD

**Issue by alvarag** [jasag/Phytoliths-recognition-system#89]
Adjunto los fallos/problemas que he detectado sobre los anexos.
[anexosC.pdf](https://github.com/jasag/Phytoliths-recognition-system/files/1117722/anexosC.pdf)

**Comment by jasag** [comment]
Muchas gracias Álvar

**Comment by alvarag** [comment]
Modifica el Readme para que como autora aparezca también Virginia

**Comment by jasag** [comment]
Está cambiado.
