### ISSUE TITLE
Poster

### ISSUE THREAD

**Issue by jasag** [jasag/Phytoliths-recognition-system#90]
Realización del poster para la presentación del proyecto.

**Comment by jasag** [comment]
@alvarag @joseFranciscoDiez ¿Qué os parece el [poster.pdf](https://github.com/jasag/Phytoliths-recognition-system/files/1122139/poster.pdf)? Me da la sensación de que esta un poco sobrecargado.

**Comment by alvarag** [comment]
Si, creo que está un poco saturado. Ideas de mejora:

- Poner el escudo arriba (junto al título) y hacer el footer más pequeño, así ganas espacio.
- Fecha pon la de presentación del póster (viernes)
- En objetivos quitaría la imagen, no aporta nada con respecto a la de conclusiones.
- Aplicaciones, pondría las tres y la imagen debajo de las tres.
- Recortar un poco el ejemplo para que no quede tan grande.

**Comment by jasag** [comment]
Gracias. En cuanto a la corrección "Aplicaciones, pondría las tres y la imagen debajo de las tres.", si lo hago así, ocupa más espacio.

**Comment by alvarag** [comment]
Te recomiendo que te pases mañana a ver las presentaciones de tus compañeros y así coger ideas.
Además podemos echar un ojo al póster si quieres.

**Comment by jasag** [comment]
Tenia idea de ello. Perfecto. He cambiado lo que me has indicado, así que mañana te lo muestro. Tiene mejor pinta.

**Comment by jasag** [comment]
![sistema de reconocimiento automatico en arqueobotanica](https://user-images.githubusercontent.com/15627268/27842247-87dbf806-6108-11e7-840a-86cac7f975fe.png)

**Comment by jasag** [comment]
Por lo tanto, la versión final del poster será la que muestro a continuación.

![sistema de reconocimiento automatico en arqueobotanica](https://user-images.githubusercontent.com/15627268/27886218-67026970-61db-11e7-9ba7-6d9bc8e626a5.png)

En el caso de que existiese alguna errata o cambio final lo notificaré en esta _issue_.
